version: '3'
services:
  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app
  #   environment:
  #     - NODE_ENV=development
  #     - POSTGRES_PASSWORD=mysecretpassword
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=mydatabase
  #   depends_on:
  #     - db
  #   command: npm run start:dev
  
  #redis:
  #  image: redis
  #  ports:
  #    - "6379:6379"
#   db:
#     image: postgres:latest
#     environment:
#       - POSTGRES_PASSWORD=mysecretpassword
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=mydatabase
#     volumes:
#       - db_data:/var/lib/postgresql/data/
#     ports:
#       - "5432:5432"
# volumes:
#   db_data:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local